###
GET http://localhost:3500/employees/2


###
POST http://localhost:3500/employees/
Content-Type: application/json

{
  "firstname": "James",
  "lastname": "BrownII"
}

###
PUT http://localhost:3500/employees
Content-Type: application/json

{
  "id": 2,
  "firstname": "Khumo"
}

###
DELETE  http://localhost:3500/employees/1

